; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:usb]
platform = espressif32
framework = arduino
board = 4d_systems_esp32s3_gen4_r8n16
board_build.sdkconfig = sdkconfig.defaults
board_build.partitions = partition.csv
board_build.filesystem = littlefs
board_build.psram_mode = octal
board_build.psram_size = 8MB
lib_deps =
	knolleary/PubSubClient@^2.8
	mrfaptastic/ESP32 HUB75 LED MATRIX PANEL DMA Display@^3.0.13
	adafruit/DHT sensor library@^1.4.6
	adafruit/Adafruit GFX Library@^1.12.1
	bblanchon/ArduinoJson@^7.4.2
	bitbank2/AnimatedGIF@^2.2.0
	marian-craciunescu/ESP32Ping@^1.7
upload_port = COM10
upload_speed = 600000
monitor_speed = 115200
build_flags =
	-DMQTT_MAX_PACKET_SIZE=1024
	-DSPIRAM_DMA_BUFFER=1
	-DCORE_DEBUG_LEVEL=4

[env:ota]
platform = espressif32
framework = arduino
board = 4d_systems_esp32s3_gen4_r8n16
board_build.sdkconfig = sdkconfig.defaults
board_build.partitions = partition.csv
board_build.filesystem = littlefs
board_build.psram_mode = octal
board_build.psram_size = 8MB
lib_deps =
	knolleary/PubSubClient@^2.8
	mrfaptastic/ESP32 HUB75 LED MATRIX PANEL DMA Display@^3.0.13
	adafruit/DHT sensor library@^1.4.6
	adafruit/Adafruit GFX Library@^1.12.1
	bblanchon/ArduinoJson@^7.4.2
	bitbank2/AnimatedGIF@^2.2.0
	marian-craciunescu/ESP32Ping@^1.7
upload_protocol = espota
upload_port = ${sysenv.OTA_IP}
upload_flags =
	--auth=${sysenv.OTA_PASS}
	--timeout=4
build_flags =
	-DMQTT_MAX_PACKET_SIZE=1024
	-DSPIRAM_DMA_BUFFER=1
	-DCORE_DEBUG_LEVEL=3
